### ISSUE TITLE
Missing files on login

### ISSUE THREAD

**Issue by teka325** [setras/Yetiforce-Portal2-preinstalled#1]
Hi thanks for the solution
I installed the portal but I get the following error on the login screen
1. Asset not found: public_html/layouts/Default/modules/Base/resources/Login.js
2. Asset not found: public_html/layouts/Default/modules/Users/resources/Login.js

**Comment by setras** [comment]
that is normal 
see this issue for more information about this messages and how to get the Portal running
[https://github.com/YetiForceCompany/YetiForceCRM/issues/5295](https://github.com/YetiForceCompany/YetiForceCRM/issues/5295)

**Comment by teka325** [comment]
Thanks for your response, how do I change the request path?
The requested URL /webservice/Users/Login was not found on this server.

**Comment by setras** [comment]
do you hve your own YF installation?
Which YF version are you using?

Have a look here https://github.com/YetiForceCompany/YetiForceCRM/issues/5295#issuecomment-335638992

BTW - webservice on https://gitstable.yetiforce.com/ is no longer working
